# Generated by Django 3.0.4 on 2020-03-14 23:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_auto_20200314_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 14, 23, 4, 8, 100649)),
        ),
        migrations.AlterField(
            model_name='interview',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 14, 23, 4, 8, 100607)),
        ),
    ]
