# Generated by Django 3.0.4 on 2020-03-15 04:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_auto_20200315_0434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='candidates',
        ),
        migrations.AddField(
            model_name='interview',
            name='candidates',
            field=models.ManyToManyField(related_name='candidates', to='src.Candidate'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 15, 4, 42, 48, 171077)),
        ),
        migrations.AlterField(
            model_name='interview',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 15, 4, 42, 48, 171036)),
        ),
    ]
